// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  articles_page_net: dynamic(() => import("./ArticlesPageNet")),
  contact_form: dynamic(() => import("./ContactForm")),
  image: dynamic(() => import("./Image")),
  quote: dynamic(() => import("./Quote")),
  text: dynamic(() => import("./Text")),
};
